package com.demo.model;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;

import java.util.ArrayList;
import java.util.List;

@Entity(tableName = "PRODUCT")
public class Product {

    @PrimaryKey(autoGenerate = true) //key autogenerated by Room
    private int id;

    @NonNull
    private String name;
    @NonNull
    private Double price;

    //add empty constructor and getter/setter


    public Product() {
    }

    @Ignore
    public Product(@NonNull String name, @NonNull Double price) {
        this.name = name;
        this.price = price;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @NonNull
    public String getName() {
        return name;
    }

    public void setName(@NonNull String name) {
        this.name = name;
    }

    @NonNull
    public Double getPrice() {
        return price;
    }

    public void setPrice(@NonNull Double price) {
        this.price = price;
    }

    public static Product[] initialiseData(){
        Product[] productSample = new Product[]{new Product("Tea", 1.25),
                new Product("Coffee", 2.50),
                new Product("Coke", 1.00),
                new Product("Juice", 3.25)};
        return productSample;
    }
}
